- name: Ensure firewalld is installed on Rocky
  ansible.builtin.yum:
    name: firewalld
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Ensure firewalld is installed on Ubuntu
  ansible.builtin.apt:
    name: firewalld
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Open necessary ports for Tomcat Server with firewalld on all systems
  ansible.builtin.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: yes
  loop:
    - 8008/tcp
    - 8009/tcp
  when: inventory_hostname in groups['tomcat_servers']

- name: Open necessary ports for Apache Server with firewalld on all systems
  ansible.builtin.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: yes
  loop:
    - 80/tcp
  when: inventory_hostname in groups['apache_servers']
