---
- name: Install Podman on Debian
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"
  become: yes

- name: Install Podman on RHEL
  ansible.builtin.yum:
    name: podman
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  become: yes

- name: Ensure ~/tomcat_container directory exists
  ansible.builtin.file:
    path: "{{ container.dest }}"
    state: directory
    mode: '0755'

- name: Copy Dockerfile to remote server
  ansible.builtin.copy:
    src: Dockerfile
    dest: "{{ container.dest }}/Dockerfile"
    mode: '0644'

- name: Copy sample.war to remote server
  ansible.builtin.copy:
    src: sample.war
    dest: "{{ container.dest }}/sample.war"
    mode: '0644'

- name: Build Tomcat container image with Podman
  containers.podman.podman_image:
    path: "{{ container.dest }}"
    name: "{{ image.name }}"
    build:
      format: "{{ image.format }}"

- name: Run a Tomcat container instance 'demo1' on port 8008 for load balancing
  containers.podman.podman_container:
    name: "{{ container_instances.demo1.name }}"
    image: "{{ image.name }}"
    state: started
    ports:
      - "{{ container_instances.demo1.port }}"

- name: Run another Tomcat container instance 'demo2' on port 8009 for load balancing
  containers.podman.podman_container:
    name: "{{ container_instances.demo2.name }}"
    image: "{{ image.name }}"
    state: started
    ports:
      - "{{ container_instances.demo2.port }}"
